export const PATHS = {
  onboarding: {
    root: '/onboarding',
    splash: '/onboarding/splash',
    privacyPromise: '/onboarding/privacy-promise',
    setupCredentials: '/onboarding/setup',
    privacyDemo: '/onboarding/privacy-demo',
    chipIntro: '/onboarding/chip-intro',
    simulatedDashboard: '/onboarding/simulated-dashboard',
    letUsKnowYou: '/onboarding/let-us-know-you',
    start: '/onboarding/start',
    account: '/onboarding/account',
    demoVault: '/onboarding/demo-vault',
    lifeHousehold: '/onboarding/life-household',
    addAccounts: '/onboarding/add-accounts',
    backupSetup: '/onboarding/backup-setup'
  },
  app: {
    root: '/app',
    home: '/app/home',
    portfolio: '/app/portfolio',
    expenses: '/app/expenses',
    goals: '/app/goals',
    insurance: '/app/insurance',
    subscriptions: '/app/subscriptions',
    loans: '/app/loans',
    tax: '/app/tax',
    cashflow: '/app/cashflow',
    chip: '/app/chip',
    backup: '/app/backup',
    import: '/app/import',
    accounts: '/app/accounts',
    calculators: '/app/calculators',
    changePin: '/app/change-pin',
    changePassphrase: '/app/change-passphrase',
    safeMode: '/app/safe-mode',
    profile: '/app/profile',
    settings: '/app/settings',
    timeline: '/app/timeline',
    news: '/app/news',
    feedback: '/app/feedback'
  }
} as const;
