// Finance-tuned sentiment lexicon (Phase A, bundled, offline). Deliberately small and headline-focused.
// Inspired by the Loughran–McDonald finance word lists + VADER-style negation/intensifier rules, tuned
// for Indian market language. This is a PUBLIC word list — no user data is involved. It can later be
// refreshed from the API-proxy worker (see docs/MARKET_SENTIMENT_RESEARCH.md §2.2), like the planned
// merchant dictionary.
//
// Weights: 1 = ordinary sentiment word, 2 = strong directional market verb. Keep entries lowercase.

export const POSITIVE: Record<string, number> = {
  // directional market verbs (strong)
  surge: 2,
  surges: 2,
  surged: 2,
  jump: 2,
  jumps: 2,
  jumped: 2,
  rally: 2,
  rallies: 2,
  rallied: 2,
  soar: 2,
  soars: 2,
  soared: 2,
  rebound: 2,
  rebounds: 2,
  rebounded: 2,
  rebounding: 2,
  // gains / rises
  gain: 1,
  gains: 1,
  gained: 1,
  rise: 1,
  rises: 1,
  rose: 1,
  rising: 1,
  climb: 1,
  climbs: 1,
  climbed: 1,
  higher: 1,
  up: 1,
  recover: 1,
  recovers: 1,
  recovery: 1,
  advance: 1,
  advances: 1,
  // fundamentals / news
  profit: 1,
  profits: 1,
  growth: 1,
  grow: 1,
  grew: 1,
  beat: 1,
  beats: 1,
  record: 1,
  strong: 1,
  robust: 1,
  upgrade: 1,
  upgrades: 1,
  upgraded: 1,
  outperform: 1,
  bullish: 2,
  boost: 1,
  boosts: 1,
  boosted: 1,
  win: 1,
  wins: 1,
  approval: 1,
  approved: 1,
  approves: 1,
  expand: 1,
  expands: 1,
  expansion: 1,
  optimism: 1,
  optimistic: 1,
  multibagger: 2,
  dividend: 1,
  buyback: 1,
  // additional common headline vocabulary
  magnificent: 1,
  strengthen: 1,
  strengthens: 1,
  strengthened: 1,
  accelerate: 1,
  accelerates: 1,
  outperforms: 1,
  outperformed: 1,
  bull: 1,
  buoyant: 1,
  cheer: 1,
  cheers: 1,
  cheered: 1,
  eases: 1,
  ease: 1,
  eased: 1,
  resilient: 1,
  resilience: 1,
  topped: 1,
  tops: 1,
  bumper: 2,
  windfall: 1,
  breakout: 1,
  milestone: 1,
  turnaround: 1
};

export const NEGATIVE: Record<string, number> = {
  // directional market verbs (strong)
  plunge: 2,
  plunges: 2,
  plunged: 2,
  tumble: 2,
  tumbles: 2,
  tumbled: 2,
  slump: 2,
  slumps: 2,
  slumped: 2,
  crash: 2,
  crashes: 2,
  crashed: 2,
  plummet: 2,
  plummets: 2,
  plummeted: 2,
  selloff: 2,
  'sell-off': 2,
  // falls / declines
  fall: 1,
  falls: 1,
  fell: 1,
  drop: 1,
  drops: 1,
  dropped: 1,
  decline: 1,
  declines: 1,
  declined: 1,
  sink: 1,
  sinks: 1,
  sank: 1,
  slide: 1,
  slides: 1,
  slid: 1,
  slip: 1,
  slips: 1,
  slipped: 1,
  lower: 1,
  down: 1,
  drag: 1,
  drags: 1,
  dragged: 1,
  // fundamentals / news
  loss: 1,
  losses: 1,
  miss: 1,
  misses: 1,
  missed: 1,
  weak: 1,
  weakness: 1,
  cut: 1,
  cuts: 1,
  downgrade: 1,
  downgrades: 1,
  downgraded: 1,
  bearish: 2,
  fraud: 2,
  scam: 2,
  probe: 1,
  ban: 1,
  banned: 1,
  default: 1,
  penalty: 1,
  fine: 1,
  fined: 1,
  layoff: 1,
  layoffs: 1,
  slowdown: 1,
  recession: 2,
  worst: 1,
  warn: 1,
  warns: 1,
  warning: 1,
  concern: 1,
  concerns: 1,
  crisis: 2,
  hit: 1,
  hits: 1,
  halt: 1,
  halts: 1,
  npa: 1,
  haircut: 1,
  // additional common headline vocabulary
  crumble: 2,
  crumbles: 2,
  crumbling: 2,
  pressure: 1,
  pressured: 1,
  weaken: 1,
  weakens: 1,
  weakened: 1,
  weakening: 1,
  struggle: 1,
  struggles: 1,
  struggling: 1,
  woes: 1,
  woe: 1,
  sluggish: 1,
  gloom: 1,
  gloomy: 1,
  bear: 1,
  selloffs: 2,
  dip: 1,
  dips: 1,
  dipped: 1,
  shrink: 1,
  shrinks: 1,
  shrank: 1,
  contraction: 1,
  downturn: 1,
  turmoil: 2,
  jitters: 1,
  fears: 1,
  fear: 1,
  panic: 2,
  rout: 2,
  crackdown: 1,
  freeze: 1,
  frozen: 1,
  writeoff: 1,
  'write-off': 1,
  bankruptcy: 2,
  insolvency: 2,
  stress: 1,
  distress: 2,
  underperform: 1,
  underperforms: 1,
  disappoint: 1,
  disappoints: 1,
  disappointing: 1,
  drought: 1,
  scandal: 2
};

/** Words that scale the magnitude of the next sentiment word. */
export const INTENSIFIERS: Record<string, number> = {
  sharply: 1.5,
  sharp: 1.5,
  steeply: 1.5,
  steep: 1.5,
  heavily: 1.5,
  significantly: 1.5,
  strongly: 1.5,
  deeply: 1.5,
  massively: 1.5
};

/** Words that flip the polarity of a nearby sentiment word (within a small window). */
export const NEGATORS = new Set<string>([
  'no',
  'not',
  "n't",
  'never',
  'without',
  'fails',
  'fail',
  'failed',
  'denies',
  'denied',
  'avoid',
  'avoids'
]);

/** How many tokens after a negator/intensifier the effect can reach. */
export const EFFECT_WINDOW = 3;
