const fs = require('fs');
const path = require('path');
const { withDangerousMod } = require('expo/config-plugins');

// Real-device crash, 2026-08-29: a release build (R8 minification on, `enableMinifyInReleaseBuilds`
// in app.json) crashed on every launch with `TypeError: Cannot read property 'create' of undefined`
// immediately after `librnscreens.so` loaded, confirmed via `adb logcat` — a debug build of the exact
// same JS bundle ran fine, isolating this to R8 specifically. Unlike `react-native-reanimated` (whose
// keep rule already existed in `android/app/proguard-rules.pro` — likely from the Expo template's own
// boilerplate, not this repo), `react-native-screens` ships no consumer proguard rules of its own
// (confirmed: no `proguard-rules.pro` under its own `android/` folder, unlike reanimated's), so nothing
// protects its native registration classes from R8 renaming/stripping them once minification is on.
//
// `android/app/proguard-rules.pro` is gitignored (regenerated by every `expo prebuild`, same reason
// `withSmsPermissions.js`/`withAbiSplits.js` exist for the manifest/build.gradle) — a rule hand-edited
// directly into it would be silently lost on the next prebuild. This plugin appends the missing rule
// via `withDangerousMod`, the standard expo-config-plugins hook for modifying an arbitrary generated
// file, so it survives every regeneration instead.
const RNSCREENS_KEEP_RULE = '-keep class com.swmansion.rnscreens.** { *; }';

module.exports = function withProguardRules(config) {
  return withDangerousMod(config, [
    'android',
    (config) => {
      const proguardPath = path.join(config.modRequest.platformProjectRoot, 'app', 'proguard-rules.pro');
      const existing = fs.existsSync(proguardPath) ? fs.readFileSync(proguardPath, 'utf8') : '';
      if (!existing.includes(RNSCREENS_KEEP_RULE)) {
        fs.appendFileSync(
          proguardPath,
          `\n# react-native-screens (see this plugin's own doc comment)\n${RNSCREENS_KEEP_RULE}\n`
        );
      }
      return config;
    }
  ]);
};
